# From Python to Numpy

indexing vs fancy indexing

In [11]:
import numpy as np

# indexing
Z = np.zeros(9)
Z_view = Z[:3]
Z[:3][...] = 1
Z

# fancy indexing
# Z = np.zeros(9)
# Z_copy = Z[[0,1,2]]
# Z_copy[...] = 1
# Z

array([1., 1., 1., 0., 0., 0., 0., 0., 0.])

In [13]:
Z_view.base

array([1., 1., 1., 0., 0., 0., 0., 0., 0.])

In [14]:
Z

array([1., 1., 1., 0., 0., 0., 0., 0., 0.])

In [15]:
Z_copy.base

## Code Vectorization

In [18]:
%%timeit
def add_python(Z1,Z2):
    return [z1+z2 for (z1,z2) in zip(Z1,Z2)]

def add_numpy(z1, z2):
    return np.add(z1, z2)

z1 = z2 = [1, 2, 3]
add_numpy(z1, z2)

1.37 µs ± 8.61 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
%%timeit
z1 = z2 = [1, 2, 3]
add_python(z1, z2)

270 ns ± 4.36 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Uniform Vectorization
all elements share the same computation at every time step with no specific processing for any element

The Game of Life
---
1. Any live cell with fewer than two live neighbours dies, as if by needs caused by underpopulation.
2. Any live cell with more than three live neighbours dies, as if by overcrowding.
3. Any live cell with two or three live neighbours lives, unchanged, to the next generation.
4. Any dead cell with exactly three live neighbours becomes a live cell.


In [33]:
# the game of life

Z = np.random.choice(
    [1, 0], size=(6,6), p=[.5, .5]
)
Z

In [43]:
def compute_neighbors(Z):
    pass

ZZ = np.full(len(Z) + 2, -1)
ZZ[1:-1] = Z
print(ZZ[:-2])
print(ZZ[1:-1])
print(ZZ[2:])

# 1. Any live cell with fewer than two live neighbours 
# dies, as if by needs caused by underpopulation.


# 2. Any live cell with more than three live 
# neighbours dies, as if by overcrowding.

# 3. Any live cell with two or three live 
# neighbours lives, unchanged, to the next generation.

# 4. 4. Any dead cell with exactly three live 
# neighbours becomes a live cell.

[-1  1  0  1  0  1]
[1 0 1 0 1 1]
[ 0  1  0  1  1 -1]
